(** {1 Day 22: Monkey Market - Secret Number Trading Challenge}

    This module solves Advent of Code Day 22 challenge about predicting buyer
    behavior in a monkey market. The module analyzes pseudorandom sequences of
    secret numbers and price patterns to maximize banana trades.

    {2 Problem Details}

    - {b Input:} Initial secret numbers for each buyer in the Monkey Exchange
      Market
    - {b Part 1:} Calculate sum of 2000th secret number generated by each
      buyer's algorithm
    - {b Part 2:} Find optimal price pattern to maximize banana trades across
      all buyers

    {2 Secret Number Evolution Process}
    Each secret number evolves through a three-step process:

    - Multiply by 64, mix (XOR), and prune (modulo 16777216)
    - Divide by 32, mix (XOR), and prune (modulo 16777216)
    - Multiply by 2048, mix (XOR), and prune (modulo 16777216)

    {b Implementation Note:} The solution uses parallel processing and efficient
    data structures for performance optimization.

    @see <https://adventofcode.com/2024/day/22> Advent of Code 2024, Day 22 *)

open Domainslib

(** [step secret] evolves a secret number once:

    + Multiply by 64, mix (XOR), and prune (modulo 16777216)
    + Divide by 32, mix (XOR), and prune (modulo 16777216)
    + Multiply by 2048, mix (XOR), and prune (modulo 16777216)

    Pruning keeps secrets below 2{^24}, so even [secret * 2048] fits easily in
    a native 63-bit [int]. Unlike [Int64], native ints are never boxed, so this
    allocates nothing. Multiplying and dividing by powers of two are shifts,
    and pruning is a bit mask. *)
let step secret =
  let secret = (secret lxor (secret lsl 6)) land 0xFFFFFF in
  let secret = (secret lxor (secret lsr 5)) land 0xFFFFFF in
  (secret lxor (secret lsl 11)) land 0xFFFFFF

(** Sum of the 2000th secret number generated by each buyer. *)
let part1 initial_secrets =
  Array.fold_left
    (fun sum initial ->
      let secret = ref (Int64.to_int initial) in
      for _ = 1 to 2000 do
        secret := step !secret
      done;
      Int64.add sum (Int64.of_int !secret))
    0L initial_secrets

(** Each price change is in [-9, 9], so a pattern of four changes is a
    four-digit number in base 19: there are exactly 19{^4} possible patterns. *)
let pattern_count = 19 * 19 * 19 * 19

(** [add_buyers secrets first last totals] adds, for every buyer in
    [first .. last], the price at the {e first} occurrence of each pattern into
    [totals.(pattern)].

    [seen.(pattern)] records the last buyer that hit the pattern, so it never
    needs clearing between buyers. *)
let add_buyers secrets first last totals =
  let seen = Array.make pattern_count (-1) in
  for buyer = first to last do
    let secret = ref (Int64.to_int secrets.(buyer)) in
    let price = ref (!secret mod 10) in
    let pattern = ref 0 in
    for i = 1 to 2000 do
      secret := step !secret;
      let next_price = !secret mod 10 in
      (* Shift the newest change (as a digit 0..18) into the pattern,
         dropping the oldest. *)
      let digit = next_price - !price + 9 in
      pattern := ((!pattern * 19) + digit) mod pattern_count;
      price := next_price;
      if i >= 4 && seen.(!pattern) <> buyer then (
        seen.(!pattern) <- buyer;
        totals.(!pattern) <- totals.(!pattern) + next_price)
    done
  done

(** Maximum number of bananas obtainable with the best pattern of four price
    changes.

    The buyers are split into one contiguous range per worker. Each worker
    accumulates into its own [totals] array, so the parallel phase needs no
    locks, and the arrays are summed once at the end. *)
let part2 initial_secrets =
  let buyers = Array.length initial_secrets in
  let workers = max 1 (min buyers (Domain.recommended_domain_count ())) in
  let totals = Array.init workers (fun _ -> Array.make pattern_count 0) in
  (* The domain calling Task.run also works, so the pool needs one fewer. *)
  let pool = Task.setup_pool ~num_domains:(workers - 1) () in
  Fun.protect
    ~finally:(fun () -> Task.teardown_pool pool)
    (fun () ->
      Task.run pool (fun () ->
          Task.parallel_for pool ~chunk_size:1 ~start:0 ~finish:(workers - 1)
            ~body:(fun worker ->
              let first = worker * buyers / workers in
              let last = ((worker + 1) * buyers / workers) - 1 in
              add_buyers initial_secrets first last totals.(worker))));
  let best = ref 0 in
  for pattern = 0 to pattern_count - 1 do
    let total = Array.fold_left (fun sum t -> sum + t.(pattern)) 0 totals in
    if total > !best then best := total
  done;
  Int64.of_int !best

(** Parses the input string into an array of initial secret numbers

    - Takes a string input with one number per line and converts each line to an
      Int64.
    - Empty lines and whitespace are handled appropriately.

    @param input Raw input string with one number per line
    @return Array of Int64 values representing initial secret numbers *)
let parse input =
  String.split_on_char '\n' input
  |> List.filter (fun s -> String.trim s <> "")
  |> List.map (fun line -> Int64.of_string (String.trim line))
  |> Array.of_list
